<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مقایسه و منطق بولی
</font>
</h1>


In [2]:
import numpy as np

In [3]:
a = np.array([2, 13, -5, -3, 19, -17])
a < 7 # سمت راست مقایسه به شکل یک آرایه (,6) با مقادیر 7 در می‌آید

array([ True, False,  True,  True, False,  True])

In [4]:
a == np.sqrt(a ** 2)  # دو سمت مقایسه می‌توانند هم‌نوع نباشند اما مقایسه‌پذیر باشند

array([ True,  True, False, False,  True, False])

In [5]:
t = np.array([[10, 12, 11, 17, 15, 11, 14],
             [13, 15, 18, 21, 19, 18, 17],
             [18, 20, 21, 19, 23, 24, 22],
             [20, 23, 19, 21, 25, 22, 21]])

In [6]:
t > 20 # خروجی یک آرایه (7 ,4) با مقادیر بولی است

array([[False, False, False, False, False, False, False],
       [False, False, False,  True, False, False, False],
       [False, False,  True, False,  True,  True,  True],
       [False,  True, False,  True,  True,  True,  True]])

In [7]:
np.count_nonzero(t > 20)

10

In [8]:
np.sum(t > 20, axis=1)

array([0, 1, 4, 5])

In [9]:
np.any(t > 30)

False

In [10]:
np.all(t >= 10)

True

In [11]:
print((t >= 15) & (t <= 20))
np.sum((t >= 15) & (t <= 20))

[[False False False  True  True False False]
 [False  True  True False  True  True  True]
 [ True  True False  True False False False]
 [ True False  True False False False False]]


12

In [12]:
np.sum(~((t < 15) | (t > 20)))

12